# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f68eb5074c61d5f1ba3faa1c691ec94aca725bd27b93637a1908b768a45db17dae403faa68fd1e1d16495dd55b4432cc599ef8166d0ddc7a894fcfb030c4bc8
  #  twilio_key: AC5bb068e864539b01f20f046a8635c262
  #  twilio_auth: 189c79a9541f497d17192574166f5c53
  # # twilio_key: <%= ENV["TWILIO_ACC"] %>
  # # twilio_auth: <%= ENV["TWILIO_AUTH"] %>
  twilio_key: AC0c8ed89aea345a6a197b308d5b3bf4ac
  twilio_auth: 3234c23789fea121774095743d775e86


test:
  secret_key_base: bcda0ab7be8b399117d1f98f76f2ce6c7fbf8d3dbb0c36c8bbb6c5a03c0aec619e313e5529d07c2502c6d3c014cf9ed8ef815694a8ba4f455e11433dbbb178c0
  twilio_key: AC5bb068e864539b01f20f046a8635c262
  twilio_auth: 189c79a9541f497d17192574166f5c53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_key: <%= ENV["TWILIO_ACC"] %>
  twilio_auth: <%= ENV["TWILIO_AUTH"] %>
